# Generated by Django 4.1.3 on 2022-11-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
    ]
